services:

  db:
    image: postgres:18.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: tanto_faz_so_pra_dev
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres_db
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/18/docker

  broker:
    hostname: myrabbit
    image: rabbitmq:4.2.2-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./rabbitmqdata:/var/lib/rabbitmq/mnesia/
    environment:
      RABBITMQ_DEFAULT_USER: cueio
      RABBITMQ_DEFAULT_PASS: cueio
      RABBITMQ_DEFAULT_VHOST: /
